# coding: utf-8

"""
    My Project

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.search_service_api import SearchServiceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSearchServiceApi(unittest.TestCase):
    """SearchServiceApi unit test stubs"""

    def setUp(self):
        self.api = SearchServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_search_v1_count_get(self):
        """Test case for api_search_v1_count_get

        Search result count  # noqa: E501
        """
        pass

    def test_api_search_v1_counts_daily_get(self):
        """Test case for api_search_v1_counts_daily_get

        Search result counts by date  # noqa: E501
        """
        pass

    def test_api_search_v1_counts_hierarchy_get(self):
        """Test case for api_search_v1_counts_hierarchy_get

        Search result counts by hierarchy  # noqa: E501
        """
        pass

    def test_api_search_v1_counts_titles_get(self):
        """Test case for api_search_v1_counts_titles_get

        Search result counts by title  # noqa: E501
        """
        pass

    def test_api_search_v1_results_get(self):
        """Test case for api_search_v1_results_get

        Search results  # noqa: E501
        """
        pass

    def test_api_search_v1_suggestions_get(self):
        """Test case for api_search_v1_suggestions_get

        Search suggestions  # noqa: E501
        """
        pass

    def test_api_search_v1_summary_get(self):
        """Test case for api_search_v1_summary_get

        Search summary details  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
